#!/bin/bash
###################################################################
#Script Name    :RIGHT_PANEL                                                                                             
#Description    :Script executed in RIGHT panel of RapidSig Display
#               :interface                                                                         
#Args           :                                                                                           
#Author         :Silas Cutler                                                
#Email          :silas@BlackLab.io                                           
###################################################################

source ./game_lib.sh

while true
do
    strings -n 6 $1 | sort | uniq | scroll
    echo "----EOF----"
    sleep 2
done
